# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wjl2h6JjX2T_qHOYU5F_9P5dcOoprQH-
"""

valor = float(input('Qual o seu salário bruto?'))
def calcular_salario(valor):
  aliquota_inss = 0.08
  valor2 = valor - (valor*aliquota_inss)
  aliquota_irrf = [0, 0.075, 0.15, 0.225, 0.275]
  parcela_reduzir = [0, 158.4, 370.4, 651,73, 884,96]
  salario = [0, 2259.2, 3751.05, 4664.68]
  alimentacao = int(input('Qual o seu valor de vale alimentação:'))
  desc_alimentacao = alimentacao*0.2
  transporte = int(input('Qual o seu valor de vale transporte:'))
  if transporte <= (valor*0.03):
    desc_transporte = transporte
  else:
    desc_transporte = (valor*0.05)
  salario_liq = 0
  for n in range(0, len(salario)):
    if valor <= salario[n]:
      salario_liq = (valor2-((valor2*aliquota_irrf[n])-parcela_reduzir[n])-desc_alimentacao-desc_transporte)
    else:
      salario_liq = (valor2-((valor2*aliquota_irrf[n])-parcela_reduzir[n])-desc_alimentacao-desc_transporte)
  print(f'O seu salário liquido sera de R${salario_liq}')
  input('Press Enter to Exit')

calcular_salario(valor)

